// Hand-curated structured data extracted from
// All_Districts_Compiled_Headingwise_Tables_cleaned.xlsx.pdf
//
// Rules used while extracting:
//  - one case per court case number (latest version wins)
//  - skip rows with no case number and no cause title
//  - skip empty template rows (B1./C1. placeholders, color-only cells)
//  - assignee defaults to SACHINA when not explicitly named
//  - petitioner name on the case becomes the stub community user name
//  - hearing entries collected from pages 64-65 + 80-84

// User IDs from prod lookup
export const USERS = {
  sachina:  '69f04cf440b9fccbb2e258e8', // Sachina K, litigation
  shashwat: '69f04cf240b9fccbb2e258e4', // Shashwat, director
  nawaz:    '69f04cf540b9fccbb2e258ea', // Nawaz Hassan, litigation (Araria)
  roshin:   '69f04cf340b9fccbb2e258e6', // Roshin Jacob, litigation
};

// Litigations — court case number is the dedup key
export const LITIGATIONS = [
  {
    courtCaseNumber: 'CWJC 8153/2025',
    causeTitle: 'Rajesh Kumar Gond & Ors. vs. State of Bihar',
    petitioners: ['Rajesh Kumar Gond', 'Pankaj Sahni', 'Md. Nurmuddin', 'Naresh Yadav', 'Vikas Kumar', 'Rajnikant', 'Pawan Kumar', 'Angad Ray', 'Kameshwar Kumar', 'Sanjay Kumar'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(C)',
    district: 'Patna',
    path: 'highcourt',
    status: 'Open',
    relevantSections: 'Article 226',
    litigationMembers: ['shashwat'],
    description: 'Service matter for employment of Homeguard candidates throughout Bihar — petitioners were selected on physical test and merit list but not appointed.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CR. WJC-23754/2025',
    causeTitle: 'Manoj Kumar Sah vs. State of Bihar & Ors.',
    petitioners: ['Manoj Kumar Sah'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(Crl)',
    district: 'Patna',
    path: 'highcourt',
    status: 'Open',
    relevantSections: 'Article 227',
    litigationMembers: ['shashwat'],
    description: 'Bhagalpur cottage industry agarbatti maker’s house demolished in land dispute due to inaction / biased support of Police; petitioner and family illegally detained.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CWJC 6647/2025',
    causeTitle: 'Bihar Rajya Anganwadi Karamchari Union vs. State of Bihar',
    petitioners: ['Bihar Rajya Anganwadi Karamchari Union'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'PIL',
    district: 'Patna',
    path: 'highcourt',
    status: 'Open',
    relevantSections: 'Article 226',
    litigationMembers: ['shashwat'],
    description: 'PIL seeking regularisation, absorption and permanency of Anganwadi Workers throughout the State of Bihar.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'ABP No.1654/2025',
    causeTitle: 'Arjun Manjhi & Sadhu Manjhi vs. State of Bihar',
    petitioners: ['Arjun Manjhi', 'Sadhu Manjhi'],
    respondents: ['State of Bihar'],
    courtName: 'Additional District & Sessions Judge VI, Danapur',
    courtType: 'district',
    state: 'Bihar',
    caseType: 'ABP',
    district: 'Patna',
    path: 'criminal',
    status: 'Disposal',
    relevantSections: 'BNS 121/122/126(2)/35/3(5)',
    litigationMembers: ['sachina'],
    description: 'Anticipatory bail allowed; petitioners taken into custody despite bail order, released next day on personal bond before ACJM IV Danapur.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Token No.19418 of 2025',
    causeTitle: 'Rizwana vs. State of Bihar',
    petitioners: ['Rizwana'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(C)',
    district: 'Patna',
    path: 'highcourt',
    status: 'Pending',
    relevantSections: 'Article 21; MTP Act s.3(2)(b); MTP Rules r.3B',
    litigationMembers: ['sachina'],
    description: 'Rape victim seeking termination of 19-week pregnancy; High Court approached to constitute a medical board on her consent.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Cr. Misc. 80492/2025',
    causeTitle: 'Md. Jainuddin vs. State of Bihar',
    petitioners: ['Md. Jainuddin'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'Cr.Misc',
    district: 'Patna',
    path: 'criminal',
    status: 'Pending',
    relevantSections: 'BNS s.482',
    litigationMembers: ['sachina', 'shashwat'],
    description: 'Bail / quashing matter, filed and admitted.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'P.S. case 239/25',
    causeTitle: 'Kanchan Kumari vs. State of Bihar',
    petitioners: ['Kanchan Kumari'],
    respondents: ['State of Bihar'],
    courtName: 'Judicial Magistrate First Class, Special Judge POCSO',
    courtType: 'district',
    state: 'Bihar',
    caseType: 'POCSO',
    district: 'Patna',
    path: 'criminal',
    status: 'Open',
    relevantSections: 'POCSO s.4 & s.6; BNS s.137(2)',
    litigationMembers: ['sachina'],
    description: 'Minor girl found pregnant after going missing; statement before police and Magistrate recorded.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CWJC 18422/2025',
    causeTitle: 'Mayank Sherawat vs. Md Aryabhatta Knowledge University & Ors.',
    petitioners: ['Mayank Sherawat'],
    respondents: ['Aryabhatta Knowledge University', 'Bihar University of Health Sciences', 'National Medical Commission'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(C)',
    district: 'Patna',
    path: 'highcourt',
    status: 'Pending',
    relevantSections: 'Article 226',
    litigationMembers: ['sachina', 'shashwat'],
    description: 'Mandamus sought to allow petitioner — MBBS student of 2022 batch — to appear in 1st and 3rd Sem exams after recovery from mental-health treatment.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Cr.W.J.C No.2996 of 2025',
    causeTitle: 'Md. Abrar Ahmad vs. State of Bihar & Ors.',
    petitioners: ['Md. Abrar Ahmad'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(Crl)',
    district: 'Patna',
    path: 'criminal',
    status: 'Pending',
    relevantSections: 'Articles 226 & 227',
    litigationMembers: ['sachina', 'shashwat', 'roshin'],
    description: 'Father seeking recovery of son Mohammad Irshad Kuraisi (27) missing since 21.08.2025; SIT prayed for.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Cr.W.J.C. No.2794 of 2025',
    causeTitle: 'Dipendra Kumar Singh vs. State of Bihar & Ors.',
    petitioners: ['Dipendra Kumar Singh'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(Crl)',
    district: 'Patna',
    path: 'criminal',
    status: 'Pending',
    relevantSections: 'Articles 226 & 227',
    litigationMembers: ['sachina', 'shashwat', 'roshin'],
    description: 'Father seeking recovery of minor daughter Navya Bhardwaj (16) missing since 24.06.2025 from Bhimnagar, Supaul; SIT with AHTU/SSB/SJPU prayed for in cross-border trafficking suspicion.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CWJC No.55 of 2026',
    causeTitle: 'Tuna Devi vs. State of Bihar & Ors.',
    petitioners: ['Tuna Devi'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(C)',
    district: 'Patna',
    path: 'highcourt',
    status: 'Pending',
    relevantSections: 'Articles 226 & 227',
    litigationMembers: ['sachina', 'shashwat', 'roshin'],
    description: 'Acid-attack survivor — widow and daily-wage labourer with four minor children — seeking enhanced compensation (≥₹75 lakh) and lifelong free treatment under Laxmi v. Union of India.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CWJC No.2062 of 2026',
    causeTitle: 'Rukmani Devi & Ors. vs. State of Bihar & Ors.',
    petitioners: ['Rukmani Devi'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(C)',
    district: 'Patna',
    path: 'highcourt',
    status: 'Pending',
    relevantSections: 'Article 226',
    litigationMembers: ['sachina', 'shashwat', 'roshin'],
    description: 'Notified Shahgaddi Malin Basti slum dwellers in Patna seeking protection from eviction / electricity disconnection without compliance with Bihar Slum Policy 2011 and PMAY-U 2.0.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Cr.W.J.C No.96 of 2026',
    causeTitle: 'Murari Thakur vs. State of Bihar & Ors.',
    petitioners: ['Murari Thakur'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(Crl)',
    district: 'Patna',
    path: 'criminal',
    status: 'Pending',
    relevantSections: 'Articles 226 & 227',
    litigationMembers: ['sachina'],
    description: 'Informant / eyewitness seeking mandamus for fair investigation into Ahiyapur P.S. Case 595/2022 (s.279, 304A IPC) for death of his father by school-bus driver; chargesheet pending >3 years.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Cr.W.J.C No.197 of 2026',
    causeTitle: 'Rampreet Goswami vs. State of Bihar & Ors.',
    petitioners: ['Rampreet Goswami'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(Crl)',
    district: 'Patna',
    path: 'criminal',
    status: 'Pending',
    relevantSections: 'Articles 226 & 227',
    litigationMembers: ['sachina', 'shashwat', 'roshin'],
    description: 'Habeas-corpus father seeking recovery of daughter Ms. Manisha (25) missing from Bodhgaya since 05.09.2025 — police inaction despite written complaints to SHO Bodhgaya and DM Gaya.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Cr. Misc No.83872 of 2025',
    causeTitle: 'Rahul Kumar vs. State of Bihar',
    petitioners: ['Rahul Kumar'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'Cr.Misc',
    district: 'Patna',
    path: 'criminal',
    status: 'Withdrawn',
    relevantSections: 'BNS s.96/137(2)',
    litigationMembers: ['sachina'],
    description: 'Anticipatory bail prayer (Tatarpur P.S. 100/2025) — minor daughter of informant Asha Devi kidnapped, not yet recovered. Janman appearing for informant; bail withdrawn after Court indicated rejection.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Cr. Misc. No.78570 of 2025',
    causeTitle: 'Md Munajir vs. State of Bihar',
    petitioners: ['Md Munajir'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'Cr.Misc',
    district: 'Patna',
    path: 'criminal',
    status: 'Dismissed',
    relevantSections: 'BNS s.137(2)/126(2)/115(2)/109/74/3(5)',
    litigationMembers: ['sachina'],
    description: 'Bail prayer (Simraha P.S. 213/2025) — Janman appearing for informant Husan Ara whose 14-yr-old daughter was kidnapped, raped (hymen torn per GMCH Purnea) and abandoned in unconscious state. Bail rejected on 21.01.2026.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CWJC-4973/2026',
    causeTitle: 'Shiro Devi vs. The State of Bihar',
    petitioners: ['Shiro Devi'],
    respondents: ['State of Bihar', 'Nagar Nigam Patna City'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(C)',
    district: 'Patna',
    path: 'highcourt',
    status: 'Pending',
    relevantSections: 'Article 21; Manual Scavenging Act',
    litigationMembers: ['sachina'],
    description: 'Widow seeking justice for husband Awadhesh Kevat who died on 12.04.2025 cleaning sewer chamber under Nagar Nigam Patna City contract — zero safeguards, in violation of Dr. Balram Singh v. Union of India directions.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CR. WJC-22296/2026',
    causeTitle: 'Kiran Devi vs. State of Bihar (Principal Secretary, Home)',
    petitioners: ['Kiran Devi'],
    respondents: ['State of Bihar — Principal Secretary, Home Department'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(Crl)',
    district: 'Patna',
    path: 'criminal',
    status: 'Pending',
    relevantSections: 'Article 226',
    litigationMembers: ['sachina'],
    description: 'Mother seeking investigation in Patliputra P.S. 349/2025 — suspicious deaths of two minor children found inside a car. Petition seeks post-mortem / FSL reports, status report, and transfer to CB-CID.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'Cr. Misc. No. 89853 of 2025',
    causeTitle: 'Saquib vs. State of Bihar',
    petitioners: ['Saquib'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'Cr.Misc',
    district: 'Patna',
    path: 'criminal',
    status: 'Dismissed',
    relevantSections: 'BNS / IPC rape provisions',
    litigationMembers: ['sachina'],
    description: 'Bail prayer in rape case — Janman appearing for victim Bibi Rizwana opposing bail. Bail rejected.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CWJC-7916/2026',
    causeTitle: 'Qamruzzman & Anr. vs. State of Bihar & Ors.',
    petitioners: ['Qamruzzman'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(C)',
    district: 'Patna',
    path: 'highcourt',
    status: 'Pending',
    relevantSections: 'Bihar Land Mutation Act s.6(10); Articles 14 & 25',
    litigationMembers: ['sachina'],
    description: 'Constitutional challenge to s.6(10) Bihar Land Mutation Act 2011 insofar as it mandates probate of Muslim wills as a condition precedent for mutation — Vaishali mutation orders dated 23.08.2022 and 26.11.2022 also challenged.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'CR. WJC-1801/2024',
    causeTitle: 'Annapurna Devi vs. State of Bihar',
    petitioners: ['Annapurna Devi'],
    respondents: ['State of Bihar', 'SDO Buxar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(Crl)',
    district: 'Patna',
    path: 'criminal',
    status: 'Pending',
    relevantSections: 'Article 226',
    litigationMembers: ['sachina'],
    description: 'Petitioner claims ownership under registered sale deed dated 13.07.2010; forcibly dispossessed on 26.10.2022 pursuant to SDO Buxar order dated 20.10.2022. Restoration of possession and compensation sought.',
    isExistingCase: false,
  },
  // Araria
  {
    courtCaseNumber: 'A.B.P 1314/2025',
    causeTitle: 'Mahesh Paswan vs. State of Bihar',
    petitioners: ['Mahesh Paswan'],
    respondents: ['State of Bihar'],
    courtName: 'Sessions Court, Araria',
    courtType: 'district',
    state: 'Bihar',
    caseType: 'ABP',
    district: 'Araria',
    path: 'criminal',
    status: 'Disposal',
    litigationMembers: ['nawaz'],
    description: 'Anticipatory bail granted to the victims.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'FIR 428/25 Araria PS',
    causeTitle: 'Sajra Khatoon vs. State of Bihar',
    petitioners: ['Sajra Khatoon'],
    respondents: ['State of Bihar'],
    courtName: 'Araria Police Station',
    courtType: 'other',
    caseType: 'FIR',
    district: 'Araria',
    path: 'criminal',
    status: 'Disposal',
    litigationMembers: ['nawaz'],
    description: 'Child-trafficking case — child rescued and handed over to the family.',
    isExistingCase: false,
  },
  {
    courtCaseNumber: 'A.B.P 2014/25',
    causeTitle: 'Chandan Yadav vs. State of Bihar',
    petitioners: ['Chandan Yadav'],
    respondents: ['State of Bihar'],
    courtName: 'Sessions Court, Araria',
    courtType: 'district',
    state: 'Bihar',
    caseType: 'ABP',
    district: 'Araria',
    path: 'criminal',
    status: 'Dismissed',
    relevantSections: 'SC/ST (PoA) Act',
    litigationMembers: ['nawaz'],
    description: 'Anticipatory bail of accused (FIR 02/25 SC/ST P.S. Araria 16.01.2025) — Janman appeared for informant; bail rejected.',
    isExistingCase: false,
  },
];

// Hearings — keyed by courtCaseNumber; date in YYYY-MM-DD
export const HEARINGS = [
  {
    courtCaseNumber: 'Cr.W.J.C No.2996 of 2025',
    date: '2025-11-17',
    dailyOrderBrief: 'Court directed conversion of present criminal writ (habeas corpus) into Criminal Writ Single Judge, noting that FIR for kidnapping is registered and investigation pending; proper direction for investigation is required.',
    loggedBy: 'sachina',
  },
  {
    courtCaseNumber: 'CWJC 18422/2025',
    date: '2025-12-04',
    dailyOrderBrief: 'Respondent universities directed to file counter affidavit.',
    loggedBy: 'sachina',
  },
  {
    courtCaseNumber: 'CWJC 18422/2025',
    date: '2025-12-23',
    dailyOrderBrief: 'Bihar University of Health Sciences directed to ensure filing of counter affidavit within three weeks, in light of the request made by the Registrar of Aryabhatta Knowledge University.',
    loggedBy: 'sachina',
  },
  {
    courtCaseNumber: 'Cr.W.J.C. No.2794 of 2025',
    date: '2025-12-09',
    dailyOrderBrief: 'ADG (Weaker Section), CID, Bihar report dated 23.09.2025 placed on record — SIT constituted for recovery of victim girl. State seeks short adjournment to apprise Court of developments post-23.09.2025.',
    loggedBy: 'sachina',
  },
  {
    courtCaseNumber: 'CWJC 18422/2025',
    date: '2026-01-13',
    dailyOrderBrief: 'BUHS counter affidavit still not filed despite 23.12.2025 direction; Court expects filing by next date in view of petitioner’s pending MBBS career.',
    loggedBy: 'sachina',
  },
  {
    courtCaseNumber: 'Cr. Misc. No.78570 of 2025',
    date: '2026-01-21',
    dailyOrderBrief: 'Bail rejected. Court not persuaded to enlarge petitioner on regular bail in view of GMCH Purnea medico-legal report (torn hymen) and victim’s s.183 BNSS statement naming petitioner in forcible abduction and rape.',
    loggedBy: 'sachina',
  },
  {
    courtCaseNumber: 'Cr. Misc No.83872 of 2025',
    date: '2026-01-22',
    dailyOrderBrief: 'Court indicated bail might be granted if petitioner produced the kidnapped minor daughter before police; petitioner’s counsel refused — bail application withdrawn before formal rejection.',
    loggedBy: 'sachina',
  },
];

// Activities — legal-aid camps, trainings, fact-finding, networking with dates
export const ACTIVITIES = [
  {
    title: 'PLV Training — Purnea',
    description: 'Para Legal Volunteers training session for Purnea district legal fellows; modules on FIR drafting, police brutality, Juvenile Justice Act, RTI Act.',
    category: 'training',
    status: 'done',
    assignee: 'sachina',
    coAssignees: [],
    dueDate: '2025-08-31',
  },
  {
    title: 'Nyaya Siksha Workshop',
    description: 'Trial advocacy and case-management training conducted with Adv. Fazal Abdali; sharpened skills on labour, SC/ST and anti-conversion matters.',
    category: 'training',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-07-12',
  },
  {
    title: 'PLV Training — Patna',
    description: 'Para Legal Volunteers training, Patna.',
    category: 'training',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-10-12',
  },
  {
    title: 'PLV Training — Patna (Nov)',
    description: 'Para Legal Volunteers training, Patna.',
    category: 'training',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-11-23',
  },
  {
    title: 'Legal Aid Camp — Patna (Nov)',
    category: 'outreach',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-11-08',
  },
  {
    title: 'Legal Aid Camp — Mahuabagh, Patna',
    category: 'outreach',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-12-06',
  },
  {
    title: 'Legal Aid Camp — Govindpur, Nandwan, Patna',
    category: 'outreach',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-12-07',
  },
  {
    title: 'Shahgaddi Slum Meeting (Contempt prep)',
    description: 'Meeting with Shahgaddi Malin Basti residents to prepare contempt application for non-compliance with CWJC 16996/2021.',
    category: 'meeting',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-10-01',
  },
  {
    title: 'Legal Aid Camp — Satbita, Araria',
    category: 'outreach',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2025-11-27',
  },
  {
    title: 'Legal Aid Camp — Farkiya Village, Raniganj, Araria',
    category: 'outreach',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2026-01-14',
  },
  {
    title: 'Talk with Ruchira Gupta',
    category: 'meeting',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2025-12-12',
  },
  {
    title: 'JJSS Volunteer Training — Araria',
    description: 'Training programme for JJSS full-time workers on FIR writing and special laws.',
    category: 'training',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2025-09-22',
  },
  {
    title: 'Fact Finding — Eviction Drive, Forbesganj',
    description: 'Fact-finding mission with JJSS on Forbesganj eviction drive; demanded resettlement and land allocation to evicted families. Procedure for eviction not followed.',
    category: 'fieldwork',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2025-05-16',
  },
  {
    title: 'Fact Finding — Custodial Death of Mithilesh Ram',
    description: 'Fact-finding on custodial death; proper medical care not given to victim.',
    category: 'fieldwork',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2025-07-20',
  },
  {
    title: 'Fact Finding — Rampur Kodarkatti Eviction',
    description: 'Eviction drive at Rampur Kodarkatti, Araria.',
    category: 'fieldwork',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2025-11-24',
  },
  {
    title: 'People’s Lawyering Workshop — Sambhavna Institute, Palampur',
    description: 'Week-long workshop on people’s lawyering at Sambhavna Institute.',
    category: 'training',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2025-12-26',
    endsAt: '2025-12-31',
  },
  {
    title: 'Madhubani Mob Lynching Fact Finding',
    category: 'fieldwork',
    status: 'done',
    assignee: 'nawaz',
    dueDate: '2026-01-22',
    endsAt: '2026-01-23',
  },
  {
    title: 'Fact Finding — Murder of Minor (Mushhar Community)',
    category: 'fieldwork',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2026-01-07',
  },
  {
    title: 'Flood Relief Training',
    description: 'Janman People’s Foundation flood relief training for fellows.',
    category: 'training',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-08-30',
  },
  {
    title: 'Samar Charitable Trust Meeting',
    category: 'meeting',
    status: 'done',
    assignee: 'sachina',
    dueDate: '2025-07-22',
  },
];
