// Second-pass additions to the PDF import — Kishanganj litigations + Patna
// pre-filing matters + advisory consults across districts as activities.
//
// Same conventions as data.mjs. No DB writes happen here.

export const EXTRA_LITIGATIONS = [
  // ---- Kishanganj ----
  {
    courtCaseNumber: 'Kuresla PS 84/2025 (CICL)',
    causeTitle: 'State v/s Aafaque Ansari (Child in Conflict with Law)',
    petitioners: ['Aafaque Ansari'],
    respondents: ['State of Bihar'],
    courtName: 'Juvenile Justice Board, Kishanganj',
    courtType: 'district',
    state: 'Bihar',
    caseType: 'JJ Act',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Open',
    litigationMembers: ['sachina'],
    description: 'JJB age-determination — CICL referred to medical for age determination as per process; record pending.',
  },
  {
    courtCaseNumber: 'Bhawanipur PS 61/24',
    causeTitle: 'Bhawanipur P.S. Case 61/24 — Reinvestigation prayer',
    petitioners: ['Informant (deceased victim\'s family)'],
    respondents: ['State of Bihar'],
    courtName: 'CJM Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'FIR',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Open',
    litigationMembers: ['sachina'],
    description: 'Reinvestigation orally directed by Court — helps in uncovering the truth and ensuring justice to the family of the deceased victim. Mother of deceased later not interested in continuing.',
  },
  {
    courtCaseNumber: 'Banmankhi PS 431/24',
    causeTitle: 'Banmankhi P.S. Case 431/24',
    petitioners: ['Accused (false-implication victim)'],
    respondents: ['State of Bihar'],
    courtName: 'Sessions Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'Bail',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Disposal',
    litigationMembers: ['sachina'],
    description: 'Classic case of illegal detention and false implication by police; regular bail granted, bail bond initially cancelled on absence of accused, later restored on hearing.',
  },
  {
    courtCaseNumber: 'Banmankhi PS 432/24',
    causeTitle: 'Banmankhi P.S. Case 432/24',
    petitioners: ['Accused (false-implication victim)'],
    respondents: ['State of Bihar'],
    courtName: 'Sessions Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'Bail',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Disposal',
    litigationMembers: ['sachina'],
    description: 'Regular bail (RB 295/25 dated 03.04.25) granted on illegal detention / false implication ground.',
  },
  {
    courtCaseNumber: 'Criminal Complaint 1651/2025',
    causeTitle: 'Criminal Complaint 1651/2025',
    petitioners: ['Complainant'],
    respondents: ['Accused'],
    courtName: 'CJM Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'Complaint',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Pending',
    litigationMembers: ['sachina'],
    description: 'Statement on oath recorded; pending enquiry witness statements.',
  },
  {
    courtCaseNumber: 'Special Excise 636/19',
    causeTitle: 'Special Excise Case 636/19',
    petitioners: ['Accused'],
    respondents: ['State of Bihar'],
    courtName: 'Special Excise Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'Excise',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Disposal',
    litigationMembers: ['sachina'],
    description: 'Fined and disposed.',
  },
  {
    courtCaseNumber: 'Sahayak Khazanchi Haat PS 108/25',
    causeTitle: 'Sahayak Khazanchi Haat P.S. Case 108/25',
    petitioners: ['Victim'],
    respondents: ['Accused'],
    courtName: 'Sessions Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'Rape',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Pending',
    litigationMembers: ['sachina'],
    description: 'Rape on false pretext of marriage — protest petition filed; bail of accused rejected.',
  },
  {
    courtCaseNumber: 'CWJC 18455/2025',
    causeTitle: 'Tatarpur Panchayat Bhawan construction — Civil Writ',
    petitioners: ['Tatarpur Village Petitioners'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'WP(C)',
    district: 'Kishanganj',
    path: 'highcourt',
    status: 'Pending',
    relevantSections: 'Article 226',
    litigationMembers: ['sachina'],
    description: 'Case admitted — interim order requiring supplementary affidavit with site pictures of where Panchayat Bhawan is being constructed. Office-notes condonation-of-delay allowed.',
  },
  {
    courtCaseNumber: 'Pothia PS 37/25',
    causeTitle: 'Pothia P.S. Case 37/25 (DLF/KNE/1)',
    petitioners: ['Victim child / family'],
    respondents: ['Accused'],
    courtName: 'JJB / CJM Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'POCSO',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Disposal',
    litigationMembers: ['sachina'],
    description: 'Custody — victim went home with parents as per Board order dated 03.04.25.',
  },
  {
    courtCaseNumber: 'Kochadhaman PS 206/25',
    causeTitle: 'Kochadhaman P.S. Case 206/25 (DLF/KNE/11)',
    petitioners: ['Victim'],
    respondents: ['Accused'],
    courtName: 'JJB Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'JJ Act',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Pending',
    litigationMembers: ['sachina'],
    description: 'Accepting objection of prosecution, Board passed order not to grant bail to the accused.',
  },
  {
    courtCaseNumber: 'Mahila PS 14/25',
    causeTitle: 'Mahila P.S. Case 14/25 (DLF/KNE/12)',
    petitioners: ['Victim'],
    respondents: ['Accused'],
    courtName: 'Sessions Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'Bail Opposition',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Pending',
    litigationMembers: ['sachina'],
    description: 'Ld. District Judge passed order not to grant bail to the accused on prosecution objection.',
  },
  {
    courtCaseNumber: 'SC/ST PS 4/23',
    causeTitle: 'SC/ST P.S. Case 4/23 (DLF/KNE/7)',
    petitioners: ['Victim (SC/ST atrocity)'],
    respondents: ['Accused'],
    courtName: 'SC/ST Special Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'SC/ST (PoA)',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Pending',
    relevantSections: 'SC/ST (Prevention of Atrocities) Act',
    litigationMembers: ['sachina'],
    description: 'Evidence put forward.',
  },
  {
    courtCaseNumber: 'Pawakhali PS 53/24',
    causeTitle: 'Pawakhali P.S. Case 53/24 (DLF/KNE/16)',
    petitioners: ['Informant'],
    respondents: ['Accused'],
    courtName: 'CJM Court, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'FIR',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Open',
    litigationMembers: ['sachina'],
    description: 'Applications given to PS in-charge and Superintendent of Police to arrest accused.',
  },
  {
    courtCaseNumber: 'Traffic PS Kishanganj 19/25',
    causeTitle: 'Traffic P.S. Kishanganj Case 19/25 (DLF/KNE/19)',
    petitioners: ['Claimant'],
    respondents: ['Insurance / accused'],
    courtName: 'MACT, Kishanganj',
    courtType: 'district', state: 'Bihar',
    caseType: 'MACT',
    district: 'Kishanganj',
    path: 'criminal',
    status: 'Open',
    litigationMembers: ['sachina'],
    description: 'Police inquiry report — provided to the insurance agency.',
  },
  // ---- Patna missing-case-number entry that does have a court file ----
  {
    courtCaseNumber: 'Cr. Misc 33897/2024',
    causeTitle: 'Supplementary Affidavit — Cr. Misc 33897/2024',
    petitioners: ['Petitioner'],
    respondents: ['State of Bihar'],
    courtName: 'Patna High Court',
    courtType: 'highcourt',
    caseType: 'Cr.Misc',
    district: 'Patna',
    path: 'criminal',
    status: 'Pending',
    litigationMembers: ['shashwat'],
    description: 'Supplementary affidavit filed in Cr. Misc 33897/2024.',
  },
];

// Advisory consults / outreach work that doesn't fit `litigations` (no
// court case number) — load as activities so the work isn't lost.
export const EXTRA_ACTIVITIES = [
  // Araria advisory
  { title: 'Advice — Md Shadab (frivolous criminal case)', category: 'documentation', assignee: 'nawaz', dueDate: '2025-05-15', description: 'Walk-in advisory: frivolous criminal case.' },
  { title: 'Advice — Darshan Kumar Paswan (criminal arising from land dispute)', category: 'documentation', assignee: 'nawaz', dueDate: '2025-05-20' },
  { title: 'Advice — Md Raqueeb (rape case intake)', category: 'documentation', assignee: 'nawaz', dueDate: '2025-06-10' },
  { title: 'Written complaint to Mahila PS Araria — Ruhi Khanam (DV)', category: 'documentation', assignee: 'nawaz', dueDate: '2025-07-15' },
  { title: 'Fact-finding + counselling — Mujahid Alam (POCSO)', category: 'fieldwork', assignee: 'nawaz', dueDate: '2025-08-15' },
  { title: 'Advice — Shadman Rahmani (domestic violence)', category: 'documentation', assignee: 'nawaz', dueDate: '2025-09-10' },
  { title: 'Advice — Budhni (domestic violence)', category: 'documentation', assignee: 'nawaz', dueDate: '2025-10-10' },
  { title: 'FIR support — Sawood Alam (son named, minor accused)', category: 'documentation', assignee: 'nawaz', dueDate: '2026-01-20' },

  // Patna pre-filing / advisory
  { title: 'Police protection plea — Runi Kumari (Article 226)', category: 'court', assignee: 'sachina', description: 'Article 226 plea; petitioner\'s father died before hearing for police protection.' },
  { title: 'Sec 482 CrPc — Nassir Buraie Musa Abbas (Sudanese national)', category: 'court', assignee: 'shashwat', description: 'Additional medical documents submitted.' },
  { title: 'RTE admission case — Md Mushtaq', category: 'court', assignee: 'sachina', description: 'Admission under Right to Free and Compulsory Education Act read with corresponding Bihar Rules.' },
  { title: 'POCSO deposition — Pratigya Kumari', category: 'court', assignee: 'sachina', description: 'Section 4 & 5 POCSO Act — deposition before District Court, Patna.' },
  { title: 'Patna Hawker\'s Association — Bihar Vendors Act intervention', category: 'court', assignee: 'shashwat', description: 'Section 9 & 18 Bihar State Street Vendors (Protection of Livelihood and Regulation of Trade) Act 2012; before Executive Magistrate, Patna.' },
  { title: 'Art 226 petition — Ananye Krishnan', category: 'court', assignee: 'sachina', description: 'Article 226 of the Constitution of India — yet to be admitted.' },
  { title: 'Cr. Misc 482 BNSS — Asha Devi (disposed)', category: 'court', assignee: 'sachina', description: 'Disposed at Patna High Court.' },
  { title: 'Cr. Misc 483/484 BNSS — Husan Ara (disposed)', category: 'court', assignee: 'sachina', description: 'Disposed at Patna High Court.' },

  // Patna walk-in / casework
  { title: 'Consultation walk-in (Patna)', category: 'other', assignee: 'sachina' },
  { title: 'Show-cause notice review (wrongly issued)', category: 'documentation', assignee: 'sachina' },
  { title: 'Cyber crime — evidence collection + cyber thana liaison', category: 'fieldwork', assignee: 'sachina' },
  { title: 'Mediation — counselled both parties', category: 'meeting', assignee: 'sachina' },
  { title: 'RTI application drafting', category: 'documentation', assignee: 'sachina' },
  { title: 'Notice drafted for recovery of money', category: 'documentation', assignee: 'sachina' },
];
